name: CI

on: [push]

# Um workflow é composto de um ou mais Jobs que podem ser executados sequencialmente ou em paralelo
jobs:
    # Este Workflow contém o Job chamados "test"
  test:
    name: Run Unit Tests
    # O tipo de runner em que o job será executado
    runs-on: ubuntu-latest  
    # Steps representam a sequencia de tarefas usando o shell runners que serão executadas como parte do Job
    steps:
    - uses: actions/checkout@v1
    #  Step para instalar o NDK
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    #  Step para rodar testes unitários
    - name: Unit tests
      run: chmod +x gradlew && ./gradlew test --stacktrace
  
  
   # Este Workflow contém um único Job chamado "build"
  build:
    needs: test
    # O tipo de runner em que o job será executado
    runs-on: ubuntu-latest
    # Steps representam a sequencia de tarefas usando o shell runners que serão executadas no como parte do Job
    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8       
    # Step para Instalar o NDK
    - name: Install NDK
      run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;20.0.5594570"
    # Step para Buildar o Projeto e gerar a APK
    - name: build debug apk
      run: chmod +x gradlew && ./gradlew assembleDebug
